### ISSUE TITLE
Bintray is shutting down -> find replacement

### ISSUE THREAD

**Issue by markaren** [NTNU-IHB/FMI4j#129]

**Comment by CDerksen** [comment]
HI Lars,

I just wanted to use the FMI import for our agent-based simulations connecting to a Modellica FMU model (using our [Agent.Workbench](https://github.com/EnFlexIT/AgentWorkbench)). 
I reconngnized that their should be a version 0.36.7 available (see Bintray), but it looks like that their is no chance to download it.

Do you have any recommendations? How dificult is it to clone and build your repo (we're experienced with Maven, OSGI and eclipse, but we don't have any experience with Kotlin or gradle). Or: can the artifacts be downloaded from Maven Central somehow or is their a chance to get the current version here from github?

Thanks in advance & best wishes,
Christian

**Comment by markaren** [comment]
If you add https://dl.bintray.com/ntnu-ihb/mvn as an additional repository

```
<dependency>
  <groupId>no.ntnu.ihb.fmi4j</groupId>
  <artifactId>fmi-import</artifactId>
  <version>0.36.7</version>
  <type>pom</type>
</dependency>
```

should work until May.

However, gradle is super easy to work with. basically just clone the repo and run `/gradlew publishToMavenLocal`, the lib has now been installed in maven local cache.
