### ISSUE TITLE
The System Could Not Find The Specified Path

### ISSUE THREAD

**Issue by mrliudeveloper** [NTNU-IHB/FMI4j#132]
I was using the FMI4J toolkit on a project, but I had a problem using it. It worked fine in debug mode and threw exceptions when calling methods. I thought I was unzipping the FMU files in an asynchronous manner, was that right?

**Comment by markaren** [comment]
Uh? What error are you getting? 

Unzipping is not asynchronous, no.

**Comment by mrliudeveloper** [comment]
Oh,no! It's my fault! To bother!Thanks！
