### ISSUE TITLE
Java. IO. FileNotFoundException

### ISSUE THREAD

**Issue by mrliudeveloper** [NTNU-IHB/FMI4j#134]
Lars, I'm back.In the use of [Fmu.from (java.net.URL)] tries to use nginx build file server load Fmu file, throws  Exception[Java. IO. FileNotFoundException:C:\Users\Mr.Liu\AppData\Local\Temp\fmi4j_22DAB33C64C553D3AC12677C4AEDE2365354478909019804419\modelDescription.XML], I don't know thisTry to see if this method is correct or give me a little hint about how to use it.Thank you very much!

**Comment by markaren** [comment]
Can you share the code? Is the URL valid?  I'm assuming you are downloading a file from the internet as you are using the URL and not File argument?

**Comment by mrliudeveloper** [comment]
No problem! The code is very simple!This is my test code!
[
    public static void main(String[] args) throws IOException {
        String defaultPath = "http://localhost/08fZrGcY/22DAB33C64C553D3AC12677C4AEDE236.fmu";//nginx path,I use google can visit!
        URL url = new URL(defaultPath);
        Fmu from = Fmu.from(url);
        System.out.println(from);
    }
]

**Comment by markaren** [comment]
Never heard of a nginx path. So when you visit that url in the browser, it will download a valid FMU to your drive?

**Comment by mrliudeveloper** [comment]
Just as you said.Oh, about "nginx path" that's a valid URL on the file server I set up using nginx.

**Comment by markaren** [comment]
You say file server, but you use localhost?

**Comment by mrliudeveloper** [comment]
Yes, what's wrong with that?At present, the file server is in the local area. I use nginx to point to a folder in the local area. After this debugging, I will change it to the real file server address.

**Comment by markaren** [comment]
To be sure, you are running the code on the file server itself ? Have you tried pointing to the file you download from that link to make sure the file is valid?

**Comment by mrliudeveloper** [comment]
Thank you,Lars! You are very good!The file was a text file, and I changed its extension to FMU, which I later ignored!I was careless!
