### ISSUE TITLE
FMI4j failed to load the FMU file

### ISSUE THREAD

**Issue by 2018-Summer** [NTNU-IHB/FMI4j#138]
Hello, sorry to bother you, now I use FMI4j to load fMU file error, the following file appears, I have no experience with Java, please help to have a look。
[hs_err_pid44476.log](https://github.com/NTNU-IHB/FMI4j/files/7761020/hs_err_pid44476.log)

**Comment by markaren** [comment]
I'd suggest you to test the FMU in other tools/platforms.

**Comment by 2018-Summer** [comment]
The fmpy. GUI call works fine

**Comment by markaren** [comment]
Check other non-python based tools and check that all your dependencies are on PATH. E.g. Python.
You can use dependency walker or similar for this.

**Comment by 2018-Summer** [comment]
Do you have a good tool to check FMU files?

**Comment by markaren** [comment]
https://github.com/modelica-tools/FMUComplianceChecker/releases/tag/2.0.4

**Comment by 2018-Summer** [comment]
If this program fmucheck.win64. exe detection of FMU is not a problem, then fMU into other programs will certainly not be a problem.

**Comment by 2018-Summer** [comment]
Hello, I detected this problem, how to solve it, I am under Windows, using pythonfmu compiled fmu
[INFO][FMUCHK] No input data provided. In case of simulation initial values from FMU will be used.
[INFO][FMUCHK] Printing output file header
"time","positive_pin_i","negative_pin_i"
[INFO][FMUCHK] Model identifier for CoSimulation: Resistor_self
[INFO][FMILIB] Loading 'win64' binary with 'default' platform types
[FATAL][FMICAPI] Could not load the DLL: 找不到指定的模块。

**Comment by markaren** [comment]
Some DLL is missing from PATH. Probably Python. Please add it.

**Comment by 2018-Summer** [comment]
I see. Thank you very much for your answer

**Comment by 2018-Summer** [comment]
FMI4j failed to load pythonFMU compiled by FMU 
[FMI native bridge] Fatal: Failed to load library 'C:\Users\zbd\AppData\Local\Temp\fmi4j_Resistor(2)1423203123758737048\binaries\win64/Resistor.dll', error: 126
This Resistor.dll exists in this path, and there is no problem with checking Resistor.fmu with fmuCheck.win64.exe, but I know what causes this problem
