### ISSUE TITLE
FMI4j in a Windows environment fails to load the Resistor. DLL file

### ISSUE THREAD

**Issue by 2018-Summer** [NTNU-IHB/FMI4j#139]
[FMI native bridge] Fatal: Failed to load library 'C:\Users\zbd\AppData\Local\Temp\fmi4j_Resistor(2)1423203123758737048\binaries\win64/Resistor.dll', error: 126
This Resistor.dll exists in this path, and there is no problem with checking Resistor.fmu with fmuCheck.win64.exe, but I know what causes this problem

**Comment by markaren** [comment]
> but I know what causes this problem

Ok?

With that said, running PythonFMU FMUs using FMI4j is a common procedure at my institution and there has not been any issues.

**Comment by 2018-Summer** [comment]
Sorry, I dialed the wrong number. I don't know what caused the problem.

**Comment by markaren** [comment]
You will need to scan the dependencies of the dll, but it is weird that fmuCheck works. Did you by any chance run fmucheck with a modified PATH?

**Comment by 2018-Summer** [comment]
When you say DLL dependencies, do you mean Python packages? How should I scan?

**Comment by markaren** [comment]
Scan the Resistor.dll using e.g [ Dependency Walker](https://www.dependencywalker.com/)
