### ISSUE TITLE
Unable to load library FMI4j

### ISSUE THREAD

**Issue by FlyBoyA** [NTNU-IHB/FMI4j#145]
[FMI native bridge] Fatal: Failed to load library 'C:\Users\naqvi\AppData\Local\Temp\fmi4j_FMU10959289766485582410\binaries\win64/FMU.dll', error: 126

I was trying to load an FMU file while I was getting the error above & this is the code.
Could you please help me in this?

       `Fmu fmu = Fmu.from(new File("C:\\Users\\naqvi\\AppData\\Local\\Temp\\OpenModelica\\OMEdit\\FMU\\FMU.fmu"));
        fmu.asCoSimulationFmu().newInstance();
        CoSimulationSlave slave = fmu.asCoSimulationFmu().newInstance();

        slave.simpleSetup();

        double t = 0;
        double stop = 10;
        double stepSize = 1.0/100;
        while(t <= stop) {
            if (!slave.doStep(t, stepSize)) {
                break;
            }
            t += stepSize;
        }
        slave.terminate();
        fmu.close();
    }`

**Comment by markaren** [comment]
Does it work in other FMI importers?

Edit: By the way, you are calling `newInstance()` twice in the above code.

**Comment by FlyBoyA** [comment]
I haven't tried with other FMI importers, Maybe Could you suggest one?
and about the `newInstance()` it really doesn't have issue with it.

**Comment by markaren** [comment]
The Python library FMPy with the GUI option would be a quick way to test.

**Comment by FlyBoyA** [comment]
Yes, I have tried in FMPy and it loaded successfully!


![WhatsApp Image 2023-11-16 at 16 53 48_1cded426](https://github.com/NTNU-IHB/FMI4j/assets/124587223/5732ff29-f8b2-4487-9439-b3eec08f3d41)

**Comment by markaren** [comment]
Thats just the static information from the modelDescription. Did you try simulating the model?

**Comment by FlyBoyA** [comment]
I tried to simulate the model and got this error, do you have any suggestions?

![image](https://github.com/NTNU-IHB/FMI4j/assets/124587223/40698ea5-d689-4f38-b4da-a39fbc7de347)

**Comment by markaren** [comment]
Then there is an issue with the model. Check that it actually supports 64bit Windows. Anyhow, not an issue with the library so closing issue

**Comment by lechogt** [comment]
I am trying build a FMU file while I have no idea to achieve this task. Could you please provide me an instance to do that?

**Comment by markaren** [comment]
This isn't really the place to ask. FMI4j is an importer. You could use one of the FMI exporters listed on the official webpage.
