### ISSUE TITLE
Support C-code FMUs

### ISSUE THREAD

**Issue by markaren** [NTNU-IHB/FMI4j#47]
Would be a nice feature to have. Should not be to difficult when following the steps used for fmu2jar (create gradle skeleton -> copy sources -> run )

**Comment by Camork** [comment]
Can you detail the steps to support c-code FMU? Which resources I need to build?

**Comment by markaren** [comment]
Have a look at [https://github.com/CATIA-Systems/FMPy](FMPy), they support it.

But without looking to much into it, what I image you'll need is a C project skeleton. Either CMake or Gradle or something else cross-platform. Then at run-time update the skeleton to use the sources provided by the FMU, compile and place the .dll/.so in the FMU.
